/** Writes db/seed.sql from the JSON data files, so the database always matches the repo. */
import { writeFileSync } from "node:fs";
import { dishes, ingredients } from "../src/data.js";
import { normalize } from "../src/normalize.js";

const q = (v: string | number | undefined | null) =>
  v === undefined || v === null ? "NULL" : typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`;
const lines: string[] = ["-- Generated by scripts/seed-sql.ts. Do not edit by hand.", "BEGIN;",
  "TRUNCATE dish_alias, dish_portion, dish_ingredient, dish, ingredient;"];

for (const i of ingredients) {
  lines.push(`INSERT INTO ingredient VALUES (${[i.code, i.name, i.group, i.localNames, i.source, i.kcal, i.protein, i.fat, i.carbs, i.fiber, i.energyNote].map(q).join(", ")});`);
}
for (const d of dishes) {
  lines.push(`INSERT INTO dish VALUES (${[d.id, d.name, d.diet, d.yieldGrams, d.defaultUnit, d.assumption].map(q).join(", ")});`);
  for (const l of d.recipe) lines.push(`INSERT INTO dish_ingredient VALUES (${[d.id, l.code, l.grams].map(q).join(", ")});`);
  for (const [unit, grams] of Object.entries(d.portions)) lines.push(`INSERT INTO dish_portion VALUES (${[d.id, unit, grams].map(q).join(", ")});`);
  for (const a of new Set([d.name, ...d.aliases])) lines.push(`INSERT INTO dish_alias VALUES (${[d.id, a, normalize(a)].map(q).join(", ")});`);
}
lines.push("COMMIT;", "");
writeFileSync(new URL("../db/seed.sql", import.meta.url), lines.join("\n"));
console.log(`wrote db/seed.sql: ${ingredients.length} ingredients, ${dishes.length} dishes`);
